name: Static Analysis using cppcheck

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cppcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Cppcheck
        run: sudo apt-get install -y cppcheck

      - name: Run Cppcheck
        # --error-exitcode=1 ensures the build fails if bugs are found
        run: cppcheck --enable=warning,style,performance,portability --inconclusive --std=c++17 --error-exitcode=1 --suppress=unusedFunction -I inc/ src/
